azure-pipelines.yml

Resolves https://github.com/omen273/crosswordApp/issues/49

49: name job after API

---

azure-pipelines.yml

Resolves https://github.com/omen273/crosswordApp/issues/63

63: fix saving video in pipeline

---

app/src/androidTest/java/com/example/crosswordToLearn/BadCrosswordDataInstrumentedTest.kt
app/src/androidTest/java/com/example/crosswordToLearn/BadCrosswordStateInstrumentedTest.kt
app/src/androidTest/java/com/example/crosswordToLearn/BadImageReadingInstrumentedTest.kt
app/src/androidTest/java/com/example/crosswordToLearn/ChooseTopicsInstrumentedTest.kt
app/src/androidTest/java/com/example/crosswordToLearn/DeleteCrosswordAfterSolveInstrumentedTest.kt
app/src/androidTest/java/com/example/crosswordToLearn/DeleteCrosswordInstrumentedTest.kt
app/src/androidTest/java/com/example/crosswordToLearn/ImpossibleToBuildInstrumentedTest.kt
app/src/androidTest/java/com/example/crosswordToLearn/NotEnoughWordsBecauseTooLongInstrumentedTest.kt
app/src/androidTest/java/com/example/crosswordToLearn/NotEnoughWordsBecauseTooShortInstrumentedTests.kt
app/src/androidTest/java/com/example/crosswordToLearn/NotEnoughWordsInstrumentedTest.kt
app/src/androidTest/java/com/example/crosswordToLearn/SolveCrosswordAfterResetInstrumentedTest.kt
app/src/androidTest/java/com/example/crosswordToLearn/SolveCrosswordInstrumentedTest.kt
app/src/androidTest/java/com/example/crosswordToLearn/SolveCrosswordWithTipsInstrumentedTest.kt
app/src/androidTest/java/com/example/crosswordToLearn/SolvedCrosswordAfterFillInstrumentedTest.kt
azure-pipelines.yml

51: publish test results

---

azure-pipelines.yml

save videos from all API

---

azure-pipelines.yml

fix saving logs for different API

---

azure-pipelines.yml

disable API 28 and 30

---

app/src/androidTest/java/com/example/crosswordToLearn/BadImageReadingInstrumentedTest.kt
app/src/main/java/com/example/crosswordToLearn/GameActivity.kt

58: remove debug logging

---

app/build.gradle
app/src/main/AndroidManifest.xml
azure-pipelines.yml
library/build.gradle

legacy external storage in manifest to be compatible with API <30

---

.github/workflows/firebase.yml

15: add action to run tests on FireBase

---

.github/workflows/firebase.yml

15: remove condition - should run on master by default

---

.github/workflows/firebase.yml

Set up physical device, add manual start and move start time later

---

.github/workflows/firebase.yml

104: add retry into firebase

---

.github/workflows/firebase.yml

113: add clear data for firebase

---

.github/workflows/release_apk.yml

Resolves #9 
create release artifact on every merge to master

9: create release apk

---

.github/workflows/release_apk.yml
app/build.gradle

122: sign apk in CI

---

app/build.gradle
app/src/androidTest/java/com/omen273/crossLingo/BadCrosswordDataInstrumentedTest.kt
app/src/androidTest/java/com/omen273/crossLingo/BadCrosswordStateInstrumentedTest.kt
app/src/androidTest/java/com/omen273/crossLingo/BadImageReadingInstrumentedTest.kt
app/src/androidTest/java/com/omen273/crossLingo/ChooseTopicsInstrumentedTest.kt
app/src/androidTest/java/com/omen273/crossLingo/DeleteCrosswordAfterSolveInstrumentedTest.kt
app/src/androidTest/java/com/omen273/crossLingo/DeleteCrosswordInstrumentedTest.kt
app/src/androidTest/java/com/omen273/crossLingo/ImpossibleToBuildInstrumentedTest.kt
app/src/androidTest/java/com/omen273/crossLingo/NotEnoughWordsBecauseTooLongInstrumentedTest.kt
app/src/androidTest/java/com/omen273/crossLingo/NotEnoughWordsBecauseTooShortInstrumentedTests.kt
app/src/androidTest/java/com/omen273/crossLingo/NotEnoughWordsInstrumentedTest.kt
app/src/androidTest/java/com/omen273/crossLingo/SolveCrosswordAfterResetInstrumentedTest.kt
app/src/androidTest/java/com/omen273/crossLingo/SolveCrosswordInstrumentedTest.kt
app/src/androidTest/java/com/omen273/crossLingo/SolveCrosswordWithTipsInstrumentedTest.kt
app/src/androidTest/java/com/omen273/crossLingo/SolvedCrosswordAfterFillInstrumentedTest.kt
app/src/androidTest/java/com/omen273/crossLingo/Utils.kt
app/src/main/AndroidManifest.xml
app/src/main/cpp/Wrapper.cpp
app/src/main/java/com/omen273/crossLingo/ChooseTopicsActivity.kt
app/src/main/java/com/omen273/crossLingo/ConfigReader.kt
app/src/main/java/com/omen273/crossLingo/ConfigWriter.kt
app/src/main/java/com/omen273/crossLingo/CrosswordBuilderWrapper.kt
app/src/main/java/com/omen273/crossLingo/GameActivity.kt
app/src/main/java/com/omen273/crossLingo/MainActivity.kt
app/src/main/java/com/omen273/crossLingo/SettActivity.kt
app/src/main/java/com/omen273/crossLingo/WordsReader.kt
app/src/test/java/com/omen273/crossLingo/ExampleUnitTest.kt

123: rename to com.omen273.crossLingo

---

app/src/main/cpp/Wrapper.cpp

123: fix app name in wrapper

---

.github/workflows/release_apk.yml
app/build.gradle
library/build.gradle

131: enable mapping and save it for release

---

app/build.gradle
library/build.gradle

update to next version

---

.github/workflows/android.yml
.github/workflows/run_unit_tests.yml

177: run CI on PR to every branch

---

app/src/main/res/raw/data.json

167 add C1 words for cooking

---

app/src/main/res/raw/data.json

Same as https://github.com/omen273/crosswordApp/pull/182 but to correct branch

185 add new words

---

app/src/main/res/raw/data.json

185 animals, cooking, food & music A1

---

app/src/main/res/raw/data.json

Home all levels

---

app/src/main/res/raw/data.json

This PR replaces https://github.com/omen273/crosswordApp/pull/203 with fixes

185 education a2

---

app/src/main/res/raw/data.json

213 fix json formatting

---

app/src/main/AndroidManifest.xml

10: add link to website to indexate app

---

app/src/main/java/com/omen273/crossLingo/GameActivity.kt
app/src/main/java/com/omen273/crossLingo/SettActivity.kt
app/src/main/res/values-ru-rRU/strings.xml
app/src/main/res/values/strings.xml
library/src/main/java/org/akop/ararat/view/CrosswordView.kt

Reverts omen273/crosswordApp#267

Revert "256 add auto changing of printing mode"

---

app/build.gradle

296: change debug app name

---

app/src/androidTest/java/com/omen273/crossLingo/CheckStarCountAfterRemovingInstrumentedTest.kt
app/src/androidTest/java/com/omen273/crossLingo/FreeClueInstrumentedTest.kt
app/src/main/java/com/omen273/crossLingo/GameActivity.kt

301: fix free clue logic and crash with menu items

---

app/build.gradle
app/src/androidTest/java/com/omen273/crossLingo/FreeClueInstrumentedTest.kt
app/src/main/java/com/omen273/crossLingo/GameActivity.kt

303: fix starts number after solving and improve test

---

app/build.gradle
app/src/androidTest/java/com/omen273/crossLingo/FreeClueInstrumentedTest.kt
app/src/main/java/com/omen273/crossLingo/GameActivity.kt

305 fix clue count reading from file

---

app/build.gradle
azure-pipelines.yml
library/src/main/java/org/akop/ararat/view/CrosswordView.kt

299 solve two words

---

app/src/main/java/com/omen273/crossLingo/GameActivity.kt

290: fix review dialog crash

---

library/src/main/java/org/akop/ararat/view/inputmethod/CrosswordInputConnection.kt

309: return focus after tapping to question
